version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  
  azurite:
    image: arafato/azurite
    hostname: azurite
    ports:
      - '10000:10000'
      - '10001:10001'
    volumes:
      - ${PWD}/storage:/opt/azurite/folder